<html>
<head>
<title>TestNG:  Login Test with Chrome browser</title>
<link href="../testng.css" rel="stylesheet" type="text/css" />
<link href="../my-testng.css" rel="stylesheet" type="text/css" />

<style type="text/css">
.log { display: none;} 
.stack-trace { display: none;} 
</style>
<script type="text/javascript">
<!--
function flip(e) {
  current = e.style.display;
  if (current == 'block') {
    e.style.display = 'none';
    return 0;
  }
  else {
    e.style.display = 'block';
    return 1;
  }
}

function toggleBox(szDivId, elem, msg1, msg2)
{
  var res = -1;  if (document.getElementById) {
    res = flip(document.getElementById(szDivId));
  }
  else if (document.all) {
    // this is the way old msie versions work
    res = flip(document.all[szDivId]);
  }
  if(elem) {
    if(res == 0) elem.innerHTML = msg1; else elem.innerHTML = msg2;
  }

}

function toggleAllBoxes() {
  if (document.getElementsByTagName) {
    d = document.getElementsByTagName('div');
    for (i = 0; i < d.length; i++) {
      if (d[i].className == 'log') {
        flip(d[i]);
      }
    }
  }
}

// -->
</script>

</head>
<body>
<h2 align='center'>Login Test with Chrome browser</h2><table border='1' align="center">
<tr>
<td>Tests passed/Failed/Skipped:</td><td>6/8/0</td>
</tr><tr>
<td>Started on:</td><td>Thu Jun 26 15:44:47 GMT+07:00 2025</td>
</tr>
<tr><td>Total time:</td><td>47 seconds (47025 ms)</td>
</tr><tr>
<td>Included groups:</td><td></td>
</tr><tr>
<td>Excluded groups:</td><td></td>
</tr>
</table><p/>
<small><i>(Hover the method name to see the test class name)</i></small><p/>
<table width='100%' border='1' class='invocation-failed'>
<tr><td colspan='4' align='center'><b>FAILED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td><b>Attribute(s)</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccessFromDataProviderHashTable()'><b>loginSuccessFromDataProviderHashTable</b><br>Test class: com.anhtester.Bai34_AllureReport_testcases.LoginTest<br>Parameters: {Password=123456, Email=admin2@example.com}</td>
<td><div><pre>java.lang.AssertionError: FAIL Because Still in the Login page: expected [false] but found [true]
	at com.anhtester.keywords.WebUI.assertNotContains(WebUI.java:459)
	at com.anhtester.Bai34_AllureReport_pages.LoginPage.verifyLoginSuccess(LoginPage.java:40)
	at com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccessFromDataProviderHashTable(LoginTest.java:68)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 14 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace945691450", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace945691450'><pre>java.lang.AssertionError: FAIL Because Still in the Login page: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1590)
	at org.testng.Assert.assertFalse(Assert.java:79)
	at com.anhtester.keywords.WebUI.assertNotContains(WebUI.java:459)
	at com.anhtester.Bai34_AllureReport_pages.LoginPage.verifyLoginSuccess(LoginPage.java:40)
	at com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccessFromDataProviderHashTable(LoginTest.java:68)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
</pre></div></td>
<td>3</td>
<td>com.anhtester.Bai34_AllureReport_testcases.LoginTest@2a331b46</td></tr>
<tr>
<td title='com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccessFromDataProviderHashTable()'><b>loginSuccessFromDataProviderHashTable</b><br>Test class: com.anhtester.Bai34_AllureReport_testcases.LoginTest<br>Parameters: {Password=123456, Email=admin3@example.com}</td>
<td><div><pre>java.lang.AssertionError: FAIL Because Still in the Login page: expected [false] but found [true]
	at com.anhtester.keywords.WebUI.assertNotContains(WebUI.java:459)
	at com.anhtester.Bai34_AllureReport_pages.LoginPage.verifyLoginSuccess(LoginPage.java:40)
	at com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccessFromDataProviderHashTable(LoginTest.java:68)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 14 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1568290764", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1568290764'><pre>java.lang.AssertionError: FAIL Because Still in the Login page: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1590)
	at org.testng.Assert.assertFalse(Assert.java:79)
	at com.anhtester.keywords.WebUI.assertNotContains(WebUI.java:459)
	at com.anhtester.Bai34_AllureReport_pages.LoginPage.verifyLoginSuccess(LoginPage.java:40)
	at com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccessFromDataProviderHashTable(LoginTest.java:68)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
</pre></div></td>
<td>3</td>
<td>com.anhtester.Bai34_AllureReport_testcases.LoginTest@2a331b46</td></tr>
<tr>
<td title='com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccessFromDataProvider()'><b>loginSuccessFromDataProvider</b><br>Test class: com.anhtester.Bai34_AllureReport_testcases.LoginTest<br>Parameters: admin4@example.com, 123456</td>
<td><div><pre>java.lang.AssertionError: FAIL Because Still in the Login page: expected [false] but found [true]
	at com.anhtester.keywords.WebUI.assertNotContains(WebUI.java:459)
	at com.anhtester.Bai34_AllureReport_pages.LoginPage.verifyLoginSuccess(LoginPage.java:40)
	at com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccessFromDataProvider(LoginTest.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 14 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1179863476", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1179863476'><pre>java.lang.AssertionError: FAIL Because Still in the Login page: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1590)
	at org.testng.Assert.assertFalse(Assert.java:79)
	at com.anhtester.keywords.WebUI.assertNotContains(WebUI.java:459)
	at com.anhtester.Bai34_AllureReport_pages.LoginPage.verifyLoginSuccess(LoginPage.java:40)
	at com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccessFromDataProvider(LoginTest.java:55)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
</pre></div></td>
<td>2</td>
<td>com.anhtester.Bai34_AllureReport_testcases.LoginTest@2a331b46</td></tr>
<tr>
<td title='com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccess()'><b>loginSuccess</b><br>Test class: com.anhtester.Bai34_AllureReport_testcases.LoginTest<br>Parameters: admin123@example.com, 123456</td>
<td><div><pre>java.lang.AssertionError: FAIL Because Still in the Login page: expected [false] but found [true]
	at com.anhtester.keywords.WebUI.assertNotContains(WebUI.java:459)
	at com.anhtester.Bai34_AllureReport_pages.LoginPage.verifyLoginSuccess(LoginPage.java:40)
	at com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccess(LoginTest.java:42)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 14 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace745740538", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace745740538'><pre>java.lang.AssertionError: FAIL Because Still in the Login page: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1590)
	at org.testng.Assert.assertFalse(Assert.java:79)
	at com.anhtester.keywords.WebUI.assertNotContains(WebUI.java:459)
	at com.anhtester.Bai34_AllureReport_pages.LoginPage.verifyLoginSuccess(LoginPage.java:40)
	at com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccess(LoginTest.java:42)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
</pre></div></td>
<td>3</td>
<td>com.anhtester.Bai34_AllureReport_testcases.LoginTest@2a331b46</td></tr>
<tr>
<td title='com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccessFromDataProvider()'><b>loginSuccessFromDataProvider</b><br>Test class: com.anhtester.Bai34_AllureReport_testcases.LoginTest<br>Parameters: admin2@example.com, 123456</td>
<td><div><pre>java.lang.AssertionError: FAIL Because Still in the Login page: expected [false] but found [true]
	at com.anhtester.keywords.WebUI.assertNotContains(WebUI.java:459)
	at com.anhtester.Bai34_AllureReport_pages.LoginPage.verifyLoginSuccess(LoginPage.java:40)
	at com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccessFromDataProvider(LoginTest.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 14 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1547494214", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1547494214'><pre>java.lang.AssertionError: FAIL Because Still in the Login page: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1590)
	at org.testng.Assert.assertFalse(Assert.java:79)
	at com.anhtester.keywords.WebUI.assertNotContains(WebUI.java:459)
	at com.anhtester.Bai34_AllureReport_pages.LoginPage.verifyLoginSuccess(LoginPage.java:40)
	at com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccessFromDataProvider(LoginTest.java:55)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
</pre></div></td>
<td>3</td>
<td>com.anhtester.Bai34_AllureReport_testcases.LoginTest@2a331b46</td></tr>
<tr>
<td title='com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccessFromDataProvider()'><b>loginSuccessFromDataProvider</b><br>Test class: com.anhtester.Bai34_AllureReport_testcases.LoginTest<br>Parameters: admin1@example.com, 123456</td>
<td><div><pre>java.lang.AssertionError: FAIL Because Still in the Login page: expected [false] but found [true]
	at com.anhtester.keywords.WebUI.assertNotContains(WebUI.java:459)
	at com.anhtester.Bai34_AllureReport_pages.LoginPage.verifyLoginSuccess(LoginPage.java:40)
	at com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccessFromDataProvider(LoginTest.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 14 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace1710249083", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace1710249083'><pre>java.lang.AssertionError: FAIL Because Still in the Login page: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1590)
	at org.testng.Assert.assertFalse(Assert.java:79)
	at com.anhtester.keywords.WebUI.assertNotContains(WebUI.java:459)
	at com.anhtester.Bai34_AllureReport_pages.LoginPage.verifyLoginSuccess(LoginPage.java:40)
	at com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccessFromDataProvider(LoginTest.java:55)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
</pre></div></td>
<td>2</td>
<td>com.anhtester.Bai34_AllureReport_testcases.LoginTest@2a331b46</td></tr>
<tr>
<td title='com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccessFromDataProvider()'><b>loginSuccessFromDataProvider</b><br>Test class: com.anhtester.Bai34_AllureReport_testcases.LoginTest<br>Parameters: admin3@example.com, 123456</td>
<td><div><pre>java.lang.AssertionError: FAIL Because Still in the Login page: expected [false] but found [true]
	at com.anhtester.keywords.WebUI.assertNotContains(WebUI.java:459)
	at com.anhtester.Bai34_AllureReport_pages.LoginPage.verifyLoginSuccess(LoginPage.java:40)
	at com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccessFromDataProvider(LoginTest.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 14 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace490789470", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace490789470'><pre>java.lang.AssertionError: FAIL Because Still in the Login page: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1590)
	at org.testng.Assert.assertFalse(Assert.java:79)
	at com.anhtester.keywords.WebUI.assertNotContains(WebUI.java:459)
	at com.anhtester.Bai34_AllureReport_pages.LoginPage.verifyLoginSuccess(LoginPage.java:40)
	at com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccessFromDataProvider(LoginTest.java:55)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
</pre></div></td>
<td>3</td>
<td>com.anhtester.Bai34_AllureReport_testcases.LoginTest@2a331b46</td></tr>
<tr>
<td title='com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccessFromDataProviderHashTable()'><b>loginSuccessFromDataProviderHashTable</b><br>Test class: com.anhtester.Bai34_AllureReport_testcases.LoginTest<br>Parameters: {Password=123456, Email=admin4@example.com}</td>
<td><div><pre>java.lang.AssertionError: FAIL Because Still in the Login page: expected [false] but found [true]
	at com.anhtester.keywords.WebUI.assertNotContains(WebUI.java:459)
	at com.anhtester.Bai34_AllureReport_pages.LoginPage.verifyLoginSuccess(LoginPage.java:40)
	at com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccessFromDataProviderHashTable(LoginTest.java:68)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
... Removed 14 stack frames</pre></div><a href='#' onClick='toggleBox("stack-trace2141190432", this, "Click to show all stack frames", "Click to hide stack frames")'>Click to show all stack frames</a>
<div class='stack-trace' id='stack-trace2141190432'><pre>java.lang.AssertionError: FAIL Because Still in the Login page: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1590)
	at org.testng.Assert.assertFalse(Assert.java:79)
	at com.anhtester.keywords.WebUI.assertNotContains(WebUI.java:459)
	at com.anhtester.Bai34_AllureReport_pages.LoginPage.verifyLoginSuccess(LoginPage.java:40)
	at com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccessFromDataProviderHashTable(LoginTest.java:68)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
</pre></div></td>
<td>7</td>
<td>com.anhtester.Bai34_AllureReport_testcases.LoginTest@2a331b46</td></tr>
</table><p>
<table width='100%' border='1' class='invocation-passed'>
<tr><td colspan='4' align='center'><b>PASSED TESTS</b></td></tr>
<tr><td><b>Test method</b></td>
<td><b>Attribute(s)</b></td>
<td width="30%"><b>Exception</b></td>
<td width="10%"><b>Time (seconds)</b></td>
<td><b>Instance</b></td>
</tr>
<tr>
<td title='com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginFailWithEmailNull()'><b>loginFailWithEmailNull</b><br>Test class: com.anhtester.Bai34_AllureReport_testcases.LoginTest</td>
<td></td>
<td>3</td>
<td>com.anhtester.Bai34_AllureReport_testcases.LoginTest@2a331b46</td></tr>
<tr>
<td title='com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginSuccessFromDataProvider()'><b>loginSuccessFromDataProvider</b><br>Test class: com.anhtester.Bai34_AllureReport_testcases.LoginTest<br>Parameters: admin@example.com, 123456</td>
<td></td>
<td>5</td>
<td>com.anhtester.Bai34_AllureReport_testcases.LoginTest@2a331b46</td></tr>
<tr>
<td title='com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginFailWithEmailNullAndPasswordNull()'><b>loginFailWithEmailNullAndPasswordNull</b><br>Test class: com.anhtester.Bai34_AllureReport_testcases.LoginTest</td>
<td></td>
<td>2</td>
<td>com.anhtester.Bai34_AllureReport_testcases.LoginTest@2a331b46</td></tr>
<tr>
<td title='com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginFailWithPasswordInvalid()'><b>loginFailWithPasswordInvalid</b><br>Test class: com.anhtester.Bai34_AllureReport_testcases.LoginTest</td>
<td></td>
<td>4</td>
<td>com.anhtester.Bai34_AllureReport_testcases.LoginTest@2a331b46</td></tr>
<tr>
<td title='com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginFailWithEmailInvalid()'><b>loginFailWithEmailInvalid</b><br>Test class: com.anhtester.Bai34_AllureReport_testcases.LoginTest</td>
<td></td>
<td>4</td>
<td>com.anhtester.Bai34_AllureReport_testcases.LoginTest@2a331b46</td></tr>
<tr>
<td title='com.anhtester.Bai34_AllureReport_testcases.LoginTest.loginFailWithPasswordNull()'><b>loginFailWithPasswordNull</b><br>Test class: com.anhtester.Bai34_AllureReport_testcases.LoginTest</td>
<td></td>
<td>3</td>
<td>com.anhtester.Bai34_AllureReport_testcases.LoginTest@2a331b46</td></tr>
</table><p>
</body>
</html>